{
 "title": "Locust",
 "description": "Locust Dashboard for load test analysis",
 "tags": [ "load_test" ],
 "time": { "from": "2024-11-20T13:51:06.289Z", "to": "2024-11-20T14:14:25.284Z" },
 "templating": {
  "list": [
   {
    "name": "testplan",
    "query": "SELECT DISTINCT testplan FROM request WHERE $__timeFilter(time)"
   },
   { "name": "send_interval", "query": "5s,10s,30s,1m,10m" }
  ]
 },
 "panels": [
  { "title": "Locust", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT Req1.name, Req1.request_type as \"request type\", \n count(Req1.*) as \"requests\", \n count(Req1.exception) as \"failed\",\n (count(Req1.exception)*100.0/(select count(*) from request Req2 where Req2.request_type = Req1.request_type and Req2.name = Req1.name and $__timeFilter(Req2.time) and (Req2.testplan = '$testplan' or '$testplan' = 'All'))) as \"error percentage\", \n AVG(Req1.response_time) as \"Average\", \n percentile_cont(0.95) within group (order by Req1.response_time) as \"95 perc\", \n percentile_cont(0.99) within group (order by Req1.response_time) as \"99 perc\", \n max(Req1.response_time) \nFROM request Req1\nWHERE $__timeFilter(time) AND \n (Req1.testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY Req1.request_type, Req1.name\n\n"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name as \"request name\",\n left(exception,300) as exception,\n count(*)\nFROM \"request\" \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All') AND \n exception is not null \nGROUP BY \"name\",left(exception,300)"
    }
   ]
  },
  {
   "title": "Requests per second / Active users",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval,NULL), \n count(*)/($__interval_ms/1000.0) as \"Req/s\"\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1 \nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval,NULL), \n avg(user_count) as active_users\nFROM user_count\nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = '')\nGROUP BY 1 \nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n $__timeGroupAlias(\"time\",$__interval),\n count(*) AS \"AllRequests\"\nFROM request\nWHERE\n $__timeFilter(\"time\") AND\n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval,NULL), \n count(*)/($__interval_ms/1000.0) as \"Error rate\"\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All') and \n exception is not null\nGROUP BY 1\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n $__timeGroupAlias(\"time\",$__interval),\n count(*)\nFROM request\nWHERE\n $__timeFilter(\"time\") AND\n (testplan = '$testplan' OR '$testplan' = 'All') AND\n exception is not null\nGROUP BY 1\n"
    }
   ]
  },
  {
   "title": "Error rate %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT \nCASE cast(allRec as numeric)\n WHEN 0 THEN 0\n ELSE cast(errorRec as numeric) / cast(allRec as numeric)\nEND\nFROM (SELECT count(*) as allRec FROM request WHERE $__timeFilter(time) and (testplan = '$testplan' OR '$testplan' = 'All')) AS \"allRecords\",\n (SELECT count(*) as errorRec FROM request WHERE $__timeFilter(time) and (testplan = '$testplan' OR '$testplan' = 'All') AND exception is not null) AS \"errorRecords\""
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time,$__interval, NULL), \n name, \n count(*)/($__interval_ms/1000.0) as throughput \nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1, name \nORDER BY 1,2\n"
    }
   ]
  },
  {
   "title": "Transaction response times (average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval, NULL), \n name ,\n avg(response_time)\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1, name \nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval, NULL), \n name, \n count(*)/($__interval_ms/1000.0) as \"Error rate\"\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All') and \n exception is not null\nGROUP BY 1, name \nORDER BY 1\n"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Connections disponible",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(pg_settings_max_connections) - sum(pg_settings_superuser_reserved_connections) - sum(pg_stat_activity_count)",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Memoire par container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{container=\"postgresql\",pod=\"ecriplus-test-postgresql-0\"})",
     "legendFormat": "ecriplus-test-postgresql-0"
    }
   ]
  },
  {
   "title": "CPU par container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"postgresql\",pod=\"ecriplus-test-postgresql-0\"}[5m]))",
     "legendFormat": "ecriplus-test-postgresql-0"
    }
   ]
  },
  {
   "title": "advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Transaction response times (log)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval, NULL), \n name ,\n avg(response_time)\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1, name \nORDER BY 1, 2"
    }
   ]
  },
  {
   "title": "Transaction response times (99th pct)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(\"time\",$__interval,NULL), \n name, \n percentile_cont(0.99) within group (order by response_time) as \"99 percentile\"\nFROM request \nWHERE $__timeFilter(time) and \n (testplan = '$testplan' OR '$testplan' = 'All')\nGROUP BY 1, name\nORDER BY 1, 2\n"
    }
   ]
  }
 ]
}